var scene=UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene(); if(scene.path!="Assets/GameMain/Scenes/Level/ZombieLevel01.unity")throw new System.Exception("Wrong scene: "+scene.path);
string buildingRoot="Assets/GameMain/Res/Map/StreetBlock01/Buildings3D/";
string[] bfiles={"Building_ConvenienceStore_3D.png","Building_Apartment_3D.png","Building_Warehouse_3D.png","Building_Safehouse_3D.png"};
foreach(string fn in bfiles){string path=buildingRoot+fn;UnityEditor.AssetDatabase.ImportAsset(path,UnityEditor.ImportAssetOptions.ForceSynchronousImport);var imp=UnityEditor.AssetImporter.GetAtPath(path) as UnityEditor.TextureImporter;if(imp==null)throw new System.Exception("Missing importer: "+path);imp.textureType=UnityEditor.TextureImporterType.Sprite;imp.spriteImportMode=UnityEditor.SpriteImportMode.Single;imp.spritePixelsPerUnit=64;imp.filterMode=UnityEngine.FilterMode.Point;imp.mipmapEnabled=false;imp.textureCompression=UnityEditor.TextureImporterCompression.Uncompressed;imp.alphaIsTransparency=true;imp.wrapMode=UnityEngine.TextureWrapMode.Clamp;imp.SaveAndReimport();}
var buildingSprites=new System.Collections.Generic.Dictionary<string,UnityEngine.Sprite>();foreach(string fn in bfiles){var sp=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Sprite>(buildingRoot+fn);if(sp==null)throw new System.Exception("Missing sprite: "+fn);buildingSprites[fn]=sp;}
var visuals=UnityEngine.GameObject.Find("BuildingVisuals");if(visuals==null)throw new System.Exception("BuildingVisuals missing");int swapped=0;foreach(var sr in visuals.GetComponentsInChildren<UnityEngine.SpriteRenderer>()){string fn="";if(sr.gameObject.name.Contains("ConvenienceStore"))fn="Building_ConvenienceStore_3D.png";else if(sr.gameObject.name.Contains("Apartment"))fn="Building_Apartment_3D.png";else if(sr.gameObject.name.Contains("Warehouse"))fn="Building_Warehouse_3D.png";else if(sr.gameObject.name.Contains("Safehouse"))fn="Building_Safehouse_3D.png";if(fn!=""){sr.sprite=buildingSprites[fn];swapped++;}}
string propsRoot="Assets/GameMain/Res/Map/StreetBlock01/Polished/";var cars=new[]{new{fn="AbandonedSedan.png",ppu=42},new{fn="WreckedCar.png",ppu=42}};foreach(var car in cars){string path=propsRoot+car.fn;UnityEditor.AssetDatabase.ImportAsset(path,UnityEditor.ImportAssetOptions.ForceSynchronousImport);var imp=UnityEditor.AssetImporter.GetAtPath(path) as UnityEditor.TextureImporter;if(imp==null)throw new System.Exception("Missing importer: "+path);imp.textureType=UnityEditor.TextureImporterType.Sprite;imp.spriteImportMode=UnityEditor.SpriteImportMode.Single;imp.spritePixelsPerUnit=car.ppu;imp.filterMode=UnityEngine.FilterMode.Point;imp.mipmapEnabled=false;imp.textureCompression=UnityEditor.TextureImporterCompression.Uncompressed;imp.alphaIsTransparency=true;imp.wrapMode=UnityEngine.TextureWrapMode.Clamp;imp.SaveAndReimport();}
var ground=UnityEngine.GameObject.Find("GroundTilemap").GetComponent<UnityEngine.Tilemaps.Tilemap>();var building=UnityEngine.GameObject.Find("BuildingTilemap").GetComponent<UnityEngine.Tilemaps.Tilemap>();var obstacle=UnityEngine.GameObject.Find("ObstacleTilemap").GetComponent<UnityEngine.Tilemaps.Tilemap>();var gameplay=UnityEngine.GameObject.Find("GameplayTilemap").GetComponent<UnityEngine.Tilemaps.Tilemap>();
var reserved=new System.Collections.Generic.HashSet<UnityEngine.Vector2Int>();foreach(var p in building.cellBounds.allPositionsWithin)if(building.GetTile(p)!=null)reserved.Add(new UnityEngine.Vector2Int(p.x,p.y));foreach(var p in obstacle.cellBounds.allPositionsWithin)if(obstacle.GetTile(p)!=null)reserved.Add(new UnityEngine.Vector2Int(p.x,p.y));foreach(var p in gameplay.cellBounds.allPositionsWithin)if(gameplay.GetTile(p)!=null)reserved.Add(new UnityEngine.Vector2Int(p.x,p.y));
var candidates=new System.Collections.Generic.List<UnityEngine.Vector2Int>();foreach(var p in ground.cellBounds.allPositionsWithin){var t=ground.GetTile(p);if(t==null)continue;if(t.name=="Asphalt"||t.name=="Pavement")continue;var v=new UnityEngine.Vector2Int(p.x,p.y);if(reserved.Contains(v))continue;if(System.Math.Abs(p.x-7)<=3&&System.Math.Abs(p.y-8)<=3)continue;candidates.Add(v);}
// deterministic shuffle
var rng=new System.Random(20260930);for(int i=candidates.Count-1;i>0;i--){int j=rng.Next(i+1);var tmp=candidates[i];candidates[i]=candidates[j];candidates[j]=tmp;}
var clutter=UnityEngine.GameObject.Find("StreetClutter");if(clutter==null)clutter=new UnityEngine.GameObject("StreetClutter");for(int i=clutter.transform.childCount-1;i>=0;i--)UnityEngine.Object.DestroyImmediate(clutter.transform.GetChild(i).gameObject);
var sprites=new System.Collections.Generic.Dictionary<string,UnityEngine.Sprite>();string[] names={"DeadTree","DryGrass","DryGrassTall","Weeds","Scrub","RustBarrel","WasteBin","RockLarge","RockPile","RockTall","FallenTrunk","WoodFence","ChainFence"};foreach(string n in names){var sp=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Sprite>(propsRoot+n+".png");if(sp==null)throw new System.Exception("Missing prop sprite: "+n);sprites[n]=sp;}
var placed=new System.Collections.Generic.List<UnityEngine.Vector2Int>();int cursor=0;int total=0;
System.Action<string,int,int,float> Place=delegate(string n,int count,int gap,float scale){int made=0;for(int pass=0;pass<candidates.Count*2&&made<count;pass++){if(cursor>=candidates.Count)break;var p=candidates[cursor++];bool near=false;foreach(var q in placed)if(System.Math.Abs(p.x-q.x)+System.Math.Abs(p.y-q.y)<gap){near=true;break;}if(near)continue;var go=new UnityEngine.GameObject("Clutter_"+total.ToString("00")+"_"+n);go.transform.SetParent(clutter.transform,false);go.transform.position=ground.GetCellCenterWorld(new UnityEngine.Vector3Int(p.x,p.y,0))+new UnityEngine.Vector3(0,0,-0.08f);var sr=go.AddComponent<UnityEngine.SpriteRenderer>();sr.sprite=sprites[n];sr.sortingOrder=6;float jitter=0.88f+(float)rng.NextDouble()*0.24f;go.transform.localScale=new UnityEngine.Vector3(scale*jitter,scale*jitter,1f);placed.Add(p);made++;total++;} };
Place("DeadTree",6,3,0.92f);Place("DryGrass",13,1,0.78f);Place("DryGrassTall",7,2,0.80f);Place("Weeds",8,1,0.78f);Place("Scrub",6,2,0.82f);Place("RustBarrel",4,2,0.78f);Place("WasteBin",4,2,0.78f);Place("RockLarge",3,3,0.82f);Place("RockPile",3,2,0.80f);Place("RockTall",3,2,0.80f);Place("FallenTrunk",2,3,0.82f);Place("WoodFence",4,2,0.76f);Place("ChainFence",4,2,0.76f);
UnityEditor.EditorUtility.SetDirty(visuals);UnityEditor.EditorUtility.SetDirty(clutter);UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(scene);UnityEditor.SceneManagement.EditorSceneManager.SaveScene(scene);UnityEditor.AssetDatabase.SaveAssets();UnityEditor.AssetDatabase.Refresh();
return new{buildingsSwapped=swapped,clutterCreated=total,candidateGrassCells=candidates.Count,carsPPU=42,scene=scene.path};
