// <auto-generated> ZombieLevel02 layout data. Regenerate with level02_gen.py, or hand-edit carefully.
// Ground / Props rows are listed top (y = Height-1) to bottom (y = 0). One char = one 1x1 cell.
#if UNITY_EDITOR
using UnityEngine;

public static class ZombieLevel02LayoutData
{
    public const int Width = 64;
    public const int Height = 40;

    // # blocked grass, B building footprint, R road, y double-yellow (E-W), h white dash (E-W),
    // v white dash (N-S), S sidewalk, C plaza concrete, d dirt/alley/lot, g lawn
    public static readonly string[] Ground =
    {
        "###########################BBBBBBB#######BBBBBB##BBBBBBBBBBBBBB#", // 39
        "#BBBBBBBBBBBBBBBBBBBBBBBB##BBBBBBBdd#####BBBBBBddBBBBBBBBBBBBBB#", // 38
        "#BBBBBBBBBBBBBBBBBBBBBBBB##BBBBBBBdd#####BBBBBBddBBBBBBBBBBBBBB#", // 37
        "#BBBBBBBBBBBBBBBBBBBBBBBB##BBBBBBBdd#####BBBBBBddBBBBBBBBBBBBBB#", // 36
        "#BBBBBBBBBBBBBBBBBBBBBBBB#SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS#", // 35
        "#BBBBBBBBBBBBBBBBBBBBBBBB#SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS#", // 34
        "#BBBBBBBBBBBBBBBBBBBBBBBB#RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR#", // 33
        "#BBBBBB####BBBBBB##BBBBBB#RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR#", // 32
        "#BBBBBB####BBBBBB##BBBBBB#hhRRRRRhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#", // 31
        "#BBBBBB####BBBBBBddBBBBBB#RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR#", // 30
        "#BBBBBB####BBBBBBddBBBBBB#RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR#", // 29
        "#BBBBBB####BBBBBBddBBBBBB#SSRRvRRSSSSSSSSSSSSSSSSSSSSSSSSSSSS###", // 28
        "#BBBBBB####BBBBBBddBBBBBB#SSRRvRRSSSSSSSSSSSSSSSSSSSSSSSSSSSS###", // 27
        "#BBBBBB####CCCCCCCCCCCCCCCSSRRvRRSS#######ddddddddddddddddd#####", // 26
        "#BBBBBB####CCCCCCCCCCCCCCCSSRRvRRSS#######ddddddddddddddddd#####", // 25
        "#BBBBBB#dddCCCgggCCCgggCCCSSRRvRRSSdddd###ddddddddddddddddd#####", // 24
        "#BBBBBB#dddCCCgggCCCgggCCCSSRRvRRSSdddd###ddddddddddddddddd#####", // 23
        "#BBBBBB#dddCCCCCCCCCCCCCCCSSRRvRRSSdddd###ddddddddddddddddd#####", // 22
        "#BBBBBB####CCCCCCCCCCCCCCCSSRRvRRSS#######ddddddddddddddddd#####", // 21
        "###BBBBBB#################SSRRvRRSSBBBBBB#ddddddddddddddddd#####", // 20
        "###BBBBBBdd###############SSRRvRRSSBBBBBB#ddddddddddddddddd#####", // 19
        "###BBBBBBddBBBBBBBBBBBB###SSRRvRRSSBBBBBBBBBBBBBBBBBBBBBBBB#####", // 18
        "###BBBBBBddBBBBBBBBBBBB###SSRRvRRSSBBBBBBBBBBBBBBBBBBBBBBBB#####", // 17
        "###BBBBBBddBBBBBBBBBBBB###SSRRvRRSSBBBBBBBBBBBBBBBBBBBBBBBB#####", // 16
        "###BBBBBBddBBBBBBBBBBBB###SSRRvRRSSBBBBBBBBBBBBBBBBBBBBBBBB#####", // 15
        "##SSSSSSSSSSSSSSSSSSSSSSSSSSRRvRRSSSSSSSSBBBBBBBBBBBBBBBBBB#####", // 14
        "##SSSSSSSSSSSSSSSSSSSSSSSSSSRRvRRSSSSSSSSBBBBBBBBBBBBBBBBBB#####", // 13
        "##RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRBBBBBBBBBBBBBBBBBB#####", // 12
        "##RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRBBBBBBBBBBBBBBBBBB#####", // 11
        "##RyyyyyyyyyyyyyyyyyyyyyyyyyRRRRRyyyyyyyyBBBBBBBBBBBBBBBBBB#####", // 10
        "##RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRBBBBBBBBBBBBBBBBBB#####", // 9
        "##RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRBBBBBBBBBBBBBBBBBB#####", // 8
        "##SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSBBBBBBBBBBBBBBBBBB#####", // 7
        "##SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSBBBBBBBBBBBBBBBBBB#####", // 6
        "############dddddddddddddd###############BBBBBBBBBBBBBBBBBB#####", // 5
        "#BBBBBBB####ddddddddddddddBBBBBBBBBBBBBB#BBBBBBBBBBBBBBBBBB#####", // 4
        "#BBBBBBB####ddddddddddddddBBBBBBBBBBBBBB#BBBBBBBBBBBBBBBBBB#####", // 3
        "#BBBBBBB####ddddddddddddddBBBBBBBBBBBBBB#BBBBBBBBBBBBBBBBBB#####", // 2
        "#BBBBBBB####ddddddddddddddBBBBBBBBBBBBBB#BBBBBBBBBBBBBBBBBB#####", // 1
        "################################################################", // 0
    };

    // Blocking: W wreck(2x2 anchor) w wreck-fill N sedan(1x2 anchor) n sedan-fill F chain fence X road barricade
    // D damaged barricade Q sandbags O barrel T dead tree K rock k rock pile U tall rock J waste bin
    // Walkable decor: o puddle * blood , dry grass ; tall dry grass ^ scrub. Digits = zone gate cells.
    public static readonly string[] Props =
    {
        "...........T....................................................", // 39
        "................................................;...............", // 38
        "................................................*..............T", // 37
        "..................................^............;*...............", // 36
        "...........................;.........22..;..........Q.......,...", // 35
        ".....................................22.............Q..,.......;", // 34
        "..........................X..*......o22....**..oo...Q......*.D..", // 33
        "T.........................D........o.22.............Q....K...D..", // 32
        ".................^........X..*....o..22...*.*Q*.....Q.....*..D..", // 31
        "..........................D..........22.....oQ...n...o..Oo*.....", // 30
        "..........................X..........22......Q*..N.....**....D.U", // 29
        ".....................................22......Q......;.,..,;..D..", // 28
        "..................................,;.22......Q...............D..", // 27
        "..........J.............J..........TT.....FFFFFF...FFFFFFFF.kT..", // 26
        ".......KU...OO.;..........;..D......J...........................", // 25
        "...............T......k.,.............OK.k.*..O......O....;.....", // 24
        ".......J..;..........K......o..........T..............*........T", // 23
        "..........*.......ww...,....ww.XX......^....ww.........n........", // 22
        "...........U......Ww........Ww......;....^..Ww....QQQ^.N.*,....;", // 21
        "........................T.............................*..;......", // 20
        ".........J............^....,...*n.........................O.....", // 19
        "..............................*.N...............................", // 18
        "................................................................", // 17
        "..........................111111111............................^", // 16
        ".kJ.....................T.111111111..........................;..", // 15
        "..D................,....;.............D.........................", // 14
        "..XQ....Q...J...........O....*........D........................T", // 13
        "..D..................ww......*.*......D.*.......................", // 12
        "..Xww........*...o...Ww.........................................", // 11
        "..DWw.................................D.........................", // 10
        "..X.............n..............**.....D........................^", // 9
        "^.DO............N.o...................D.........................", // 8
        "..X,.....................X.......;....D.........................", // 7
        "..D...,.....;.;,......................D.........................", // 6
        ".......^....FFF..FFFFF..FF............^....................T....", // 5
        ".................O..............................................", // 4
        ".............ww.,...n...........................................", // 3
        "...........k.Ww...n.N..ww.......................................", // 2
        ".............;^^^.N....WwO......................................", // 1
        "...........J..........J;T..........T^................;..........", // 0
    };

    public struct BuildingDef { public string Name, Sprite; public int X, Y, W, H;
        public BuildingDef(string n, string s, int x, int y, int w, int h) { Name = n; Sprite = s; X = x; Y = y; W = w; H = h; } }
    public struct WaveDef { public string Id; public int X0, Y0, X1, Y1, Count; public string[] Spawns;
        public WaveDef(string id, int x0, int y0, int x1, int y1, int c, string[] s) { Id = id; X0 = x0; Y0 = y0; X1 = x1; Y1 = y1; Count = c; Spawns = s; } }
    public struct GateDef { public string Name; public char Mark; public string WaveId;
        public GateDef(string n, char m, string w) { Name = n; Mark = m; WaveId = w; } }
    public struct SpawnDef { public string Id; public Vector2 Position;
        public SpawnDef(string id, Vector2 p) { Id = id; Position = p; } }

    public static readonly BuildingDef[] Buildings =
    {
        new BuildingDef("Start_Safehouse", "Safehouse_CentralGate", 3, 15, 6, 6),
        new BuildingDef("Shop_A_West", "Shop_TwoUnits_A", 11, 15, 6, 4),
        new BuildingDef("Shop_B_West", "Shop_TwoUnits_B", 17, 15, 6, 4),
        new BuildingDef("Apt_A_East", "Apartment_TwoUnits_B", 35, 15, 6, 6),
        new BuildingDef("Apt_Plaza_West", "Apartment_TwoUnits_A", 11, 27, 6, 6),
        new BuildingDef("Apt_Plaza_East", "Apartment_TwoUnits_B", 19, 27, 6, 6),
        new BuildingDef("Shop_Row_North", "Building_RowShop_GptImage2", 27, 36, 7, 4),
        new BuildingDef("Shop_C_North", "Shop_TwoUnits_B", 41, 36, 6, 4),
        new BuildingDef("Apt_Low_North", "Building_LowApartment_GptImage2", 49, 36, 7, 4),
        new BuildingDef("Evac_Safehouse", "Building_SafehouseFront_GptImage2", 56, 36, 7, 4),
        new BuildingDef("Block_10_Apartment_TwoUnits_A", "Apartment_TwoUnits_A", 41, 1, 6, 6),
        new BuildingDef("Block_11_Apartment_TwoUnits_B", "Apartment_TwoUnits_B", 47, 1, 6, 6),
        new BuildingDef("Block_12_Apartment_TwoUnits_A", "Apartment_TwoUnits_A", 53, 1, 6, 6),
        new BuildingDef("Block_13_Apartment_TwoUnits_B", "Apartment_TwoUnits_B", 41, 7, 6, 6),
        new BuildingDef("Block_14_Apartment_TwoUnits_A", "Apartment_TwoUnits_A", 47, 7, 6, 6),
        new BuildingDef("Block_15_Apartment_TwoUnits_B", "Apartment_TwoUnits_B", 53, 7, 6, 6),
        new BuildingDef("Block_16_Apartment_TwoUnits_A", "Apartment_TwoUnits_A", 41, 13, 6, 6),
        new BuildingDef("Block_17_Apartment_TwoUnits_B", "Apartment_TwoUnits_B", 47, 13, 6, 6),
        new BuildingDef("Block_18_Apartment_TwoUnits_A", "Apartment_TwoUnits_A", 53, 13, 6, 6),
        new BuildingDef("Block_19_Apartment_TwoUnits_B", "Apartment_TwoUnits_B", 1, 21, 6, 6),
        new BuildingDef("Block_20_Apartment_TwoUnits_A", "Apartment_TwoUnits_A", 1, 27, 6, 6),
        new BuildingDef("Block_21_Apartment_TwoUnits_B", "Apartment_TwoUnits_B", 1, 33, 6, 6),
        new BuildingDef("Block_22_Apartment_TwoUnits_A", "Apartment_TwoUnits_A", 7, 33, 6, 6),
        new BuildingDef("Block_23_Apartment_TwoUnits_B", "Apartment_TwoUnits_B", 13, 33, 6, 6),
        new BuildingDef("Block_24_Apartment_TwoUnits_A", "Apartment_TwoUnits_A", 19, 33, 6, 6),
        new BuildingDef("Block_25_Building_LowApartment_GptImage2", "Building_LowApartment_GptImage2", 1, 1, 7, 4),
        new BuildingDef("Block_26_Building_RowShop_GptImage2", "Building_RowShop_GptImage2", 26, 1, 7, 4),
        new BuildingDef("Block_27_Building_LowApartment_GptImage2", "Building_LowApartment_GptImage2", 33, 1, 7, 4),
    };

    public static readonly SpawnDef[] Spawns =
    {
        new SpawnDef("A1", new Vector2(10.00f, 17.50f)),
        new SpawnDef("A2", new Vector2(19.50f, 3.50f)),
        new SpawnDef("A3", new Vector2(39.50f, 10.50f)),
        new SpawnDef("B1", new Vector2(37.00f, 23.50f)),
        new SpawnDef("B2", new Vector2(8.50f, 23.50f)),
        new SpawnDef("B3", new Vector2(18.00f, 29.50f)),
        new SpawnDef("B4", new Vector2(35.00f, 37.50f)),
        new SpawnDef("C1", new Vector2(48.00f, 37.50f)),
        new SpawnDef("C2", new Vector2(43.50f, 19.50f)),
        new SpawnDef("C3", new Vector2(62.50f, 30.50f)),
        new SpawnDef("C4", new Vector2(57.50f, 24.50f)),
    };

    public static readonly WaveDef[] Waves =
    {
        new WaveDef("Wave_A", 24, 6, 36, 14, 7, new[] { "A1", "A2", "A3" }),
        new WaveDef("Wave_B", 26, 18, 34, 22, 10, new[] { "B1", "B2", "B3", "B4" }),
        new WaveDef("Wave_C", 40, 27, 46, 35, 14, new[] { "C1", "C2", "C3", "C4" }),
    };

    public static readonly GateDef[] Gates =
    {
        new GateDef("Gate_1", '1', "Wave_A"),
        new GateDef("Gate_2", '2', "Wave_B"),
    };

    public static readonly string[] AmbientSpawns = { "A2", "A3" };
    public static readonly Vector2 StartDoor = new Vector2(6.00f, 14.30f);
    public static readonly Vector2 PlayerSpawn = new Vector2(6.00f, 13.50f);
    public static readonly Vector2 ExitDoor = new Vector2(59.50f, 35.40f);
}
#endif
