using System.IO;
using GameMain;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityGameFramework.Runtime;

namespace GameMain.Editor
{
    [InitializeOnLoad]
    internal static class CreateLaunchSceneOnLoad
    {
        private const string ScenePath = "Assets/GameMain/Scenes/Launch.unity";
        private const string MarkerPath = "Assets/GameMain/Editor/.launch_scene_created";

        static CreateLaunchSceneOnLoad()
        {
            EditorApplication.delayCall += CreateSceneIfNeeded;
        }

        private static void CreateSceneIfNeeded()
        {
            EditorApplication.delayCall -= CreateSceneIfNeeded;

            if (File.Exists(MarkerPath) || File.Exists(ScenePath) || EditorApplication.isPlayingOrWillChangePlaymode)
            {
                return;
            }

            Directory.CreateDirectory("Assets/GameMain/Scenes");
            Directory.CreateDirectory("Assets/GameMain/UI");
            Directory.CreateDirectory("Assets/GameMain/Configs");

            UnityEngine.SceneManagement.Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
            scene.name = "Launch";

            GameObject gameEntry = new GameObject("GameEntry");
            gameEntry.AddComponent<BaseComponent>();
            gameEntry.AddComponent<FsmComponent>();
            gameEntry.AddComponent<ProcedureComponent>();
            gameEntry.AddComponent<GameFrameworkProcedureSetup>();

            GameObject cameraObject = new GameObject("Main Camera");
            cameraObject.tag = "MainCamera";
            Camera camera = cameraObject.AddComponent<Camera>();
            camera.clearFlags = CameraClearFlags.SolidColor;
            camera.backgroundColor = new Color(0.12f, 0.13f, 0.15f);
            camera.orthographic = true;
            camera.orthographicSize = 5f;
            cameraObject.transform.position = new Vector3(0f, 0f, -10f);

            EditorSceneManager.SaveScene(scene, ScenePath);
            AddSceneToBuildSettings(ScenePath);

            File.WriteAllText(MarkerPath, "Launch scene generated by Codex for the UGF learning skeleton.");
            AssetDatabase.Refresh();
            Debug.Log("[UGF] Created learning launch scene at " + ScenePath);
        }

        private static void AddSceneToBuildSettings(string scenePath)
        {
            EditorBuildSettingsScene[] scenes = EditorBuildSettings.scenes;
            foreach (EditorBuildSettingsScene scene in scenes)
            {
                if (scene.path == scenePath)
                {
                    return;
                }
            }

            EditorBuildSettingsScene[] updatedScenes = new EditorBuildSettingsScene[scenes.Length + 1];
            scenes.CopyTo(updatedScenes, 0);
            updatedScenes[updatedScenes.Length - 1] = new EditorBuildSettingsScene(scenePath, true);
            EditorBuildSettings.scenes = updatedScenes;
        }
    }
}
